# Generated by Django 4.0.6 on 2022-08-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobs_status_alter_userlanguages_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Full professional proficiency', 'Full professional proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Elementary proficiency', 'Elementary proficiency'), ('Professional working proficiency', 'Professional working proficiency')], max_length=255),
        ),
    ]
