# Generated by Django 4.2.1 on 2023-06-15 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_alter_activestudent_answer_alter_jobs_deadline_and_more'),
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='amount',
            new_name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='duration',
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cardholder_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cvc',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='expiry_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='jobId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.jobs'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 13, 10, 58, 425958)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(max_length=255),
        ),
    ]
