# Generated by Django 4.2.1 on 2023-06-15 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0002_rename_amount_subscription_monthly_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 13, 15, 21, 778749)),
        ),
    ]
