# Generated by Django 4.0.6 on 2023-06-27 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0005_alter_subscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 10, 47, 9, 362299)),
        ),
    ]
