# Generated by Django 4.2.4 on 2023-10-17 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0010_alter_subscription_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 16, 32, 11, 943084)),
        ),
    ]
