# Generated by Django 4.0.6 on 2022-11-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_remove_search_job_id_alter_search_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=255)),
            ],
        ),
    ]
