# Generated by Django 4.0.6 on 2022-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0005_usercity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
