# Generated by Django 4.0.6 on 2022-12-07 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ScreeningQuestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestion',
            name='Ans1',
            field=models.CharField(blank=True, choices=[('Yes/No', 'Yes/No'), ('Numeric', 'Numeric')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ApplicantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ans1', models.CharField(blank=True, max_length=100, null=True)),
                ('Ans2', models.CharField(blank=True, max_length=100, null=True)),
                ('Ans3', models.CharField(blank=True, max_length=100, null=True)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreeningQuestion.jobquestion')),
            ],
        ),
    ]
