# Generated by Django 4.0.6 on 2022-12-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0002_alter_jobquestion_ans1_applicantanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestion',
            name='Ans1',
            field=models.CharField(blank=True, choices=[('Numeric', 'Numeric'), ('Yes/No', 'Yes/No')], max_length=100, null=True),
        ),
    ]
