# Generated by Django 4.0.6 on 2022-12-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0003_alter_jobquestion_ans1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestion',
            name='Ans1',
            field=models.CharField(blank=True, choices=[('Yes/No', 'Yes/No'), ('Numeric', 'Numeric')], max_length=100, null=True),
        ),
    ]
