# Generated by Django 4.0.6 on 2022-12-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0004_alter_jobquestion_ans1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantanswer',
            old_name='Ans1',
            new_name='user_answer',
        ),
        migrations.RenameField(
            model_name='jobquestion',
            old_name='jobid',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='jobquestion',
            old_name='Qualify',
            new_name='qualify',
        ),
        migrations.RenameField(
            model_name='jobquestion',
            old_name='Ans1',
            new_name='question_type',
        ),
        migrations.RemoveField(
            model_name='applicantanswer',
            name='Ans2',
        ),
        migrations.RemoveField(
            model_name='applicantanswer',
            name='Ans3',
        ),
    ]
