# Generated by Django 4.0.6 on 2022-12-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0005_rename_ans1_applicantanswer_user_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobquestion',
            name='ideal_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
