# Generated by Django 4.0.6 on 2022-12-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_application_applicantstat_alter_jobs_housing_and_more'),
        ('ScreeningQuestion', '0006_jobquestion_ideal_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('jobSettings', models.CharField(max_length=500)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobs')),
            ],
        ),
    ]
