# Generated by Django 4.1.5 on 2023-01-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0010_alter_jobquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestion',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Numeric', 'Numeric'), ('Yes/No', 'Yes/No')], max_length=100, null=True),
        ),
    ]
