# Generated by Django 4.1.1 on 2023-02-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0015_alter_jobsettings_jobsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsettings',
            name='jobSettings',
            field=models.CharField(choices=[('F', 'Filter out & send rejection letters to applicants who dont meet qualifications'), ('NF', 'Don’t filter out applicants. I will manually review each application sent to me')], max_length=500),
        ),
    ]
