# Generated by Django 4.2.4 on 2023-10-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0042_alter_jobquestion_ideal_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsettings',
            name='jobSettings',
            field=models.CharField(choices=[('F', 'Filter out & send rejection letters to applicants who dont meet qualifications'), ('NF', 'Don’t filter out applicants. I will manually review each application sent to me')], max_length=500),
        ),
    ]
