# Generated by Django 4.2.4 on 2023-10-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0045_alter_jobquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsettings',
            name='jobSettings',
            field=models.CharField(choices=[('NF', 'Don’t filter out applicants. I will manually review each application sent to me'), ('F', 'Filter out & send rejection letters to applicants who dont meet qualifications')], max_length=500),
        ),
    ]
