# Generated by Django 4.2.4 on 2023-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreeningQuestion', '0046_alter_jobsettings_jobsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestion',
            name='question_type',
            field=models.CharField(blank=True, choices=[('Numeric', 'Numeric'), ('Yes/No', 'Yes/No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobsettings',
            name='jobSettings',
            field=models.CharField(choices=[('F', 'Filter out & send rejection letters to applicants who dont meet qualifications'), ('NF', 'Don’t filter out applicants. I will manually review each application sent to me')], max_length=500),
        ),
    ]
