# Generated by Django 4.0.6 on 2022-08-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_application_status_alter_userlanguages_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='country_j',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Elementary proficiency', 'Elementary proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Professional working proficiency', 'Professional working proficiency')], max_length=255),
        ),
    ]
