# Generated by Django 4.0.6 on 2022-08-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_jobs_status_alter_userlanguages_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Elementary proficiency', 'Elementary proficiency')], max_length=255),
        ),
    ]
