# Generated by Django 4.0.6 on 2022-08-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_application_apply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='apply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], default='Pennding', max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Professional working proficiency', 'Professional working proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Elementary proficiency', 'Elementary proficiency')], max_length=255),
        ),
    ]
