# Generated by Django 4.0.6 on 2022-08-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_application_status_alter_customuser_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Elementary proficiency', 'Elementary proficiency'), ('Limited working proficiency', 'Limited working proficiency')], max_length=255),
        ),
    ]
