# Generated by Django 4.0.6 on 2022-09-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_application_status_alter_jobs_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type_of_work',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Full professional proficiency', 'Full professional proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Elementary proficiency', 'Elementary proficiency')], max_length=255),
        ),
    ]
