# Generated by Django 4.1.1 on 2022-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_picture_alter_jobs_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(default='defaultCover.jpeg', upload_to='cover'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='defaultProfile.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Ausbildung', 'Ausbildung'), ('Work And Travel', 'Work And Travel'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Professional working proficiency', 'Professional working proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Elementary proficiency', 'Elementary proficiency'), ('Limited working proficiency', 'Limited working proficiency')], max_length=255),
        ),
    ]
