# Generated by Django 4.0.6 on 2022-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_jobs_program_alter_userlanguages_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='city_j',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='country_j',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Work And Travel', 'Work And Travel'), ('Internship', 'Internship'), ('Ausbildung', 'Ausbildung')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type_of_work',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='university',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userexperiece',
            name='Country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userexperiece',
            name='city_usExp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Low-Intermediate', 'Low-Intermediate'), ('Basic', 'Basic'), ('High-Intermediate', 'High-Intermediate'), ('Advanced', 'Advanced')], max_length=255),
        ),
    ]
