# Generated by Django 4.0.6 on 2022-10-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_university_location_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Basic', 'Basic'), ('N/A', 'N/A'), ('High-Intermediate', 'High-Intermediate'), ('Low-Intermediate', 'Low-Intermediate')], max_length=255),
        ),
    ]
