# Generated by Django 4.0.6 on 2022-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_application_status_alter_jobs_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Work And Travel', 'Work And Travel'), ('Ausbildung', 'Ausbildung'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Basic', 'Basic'), ('High-Intermediate', 'High-Intermediate'), ('Low-Intermediate', 'Low-Intermediate'), ('Advanced', 'Advanced')], max_length=255),
        ),
    ]
