# Generated by Django 4.0.6 on 2022-11-28 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_jobs_postdate_alter_jobs_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Pennding', 'Pennding')], default='Pennding', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 28, 10, 6, 1, 799796), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Work and Travel', 'Work and Travel'), ('Trainee', 'Trainee'), ('Ausbildung', 'Ausbildung'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.CharField(choices=[('Master', 'Master’s Degree'), ('Bachelor', 'Bachelor’s Degree')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('N/A', 'N/A'), ('Basic', 'Basic'), ('Low-Intermediate', 'Low-Intermediate'), ('High-Intermediate', 'High-Intermediate')], max_length=255),
        ),
    ]
