# Generated by Django 4.0.6 on 2022-12-20 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_alter_activestudent_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicantStat',
            field=models.CharField(blank=True, choices=[('Qualified', 'Qualified'), ('Not qualified', 'Not qualified')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='housing',
            field=models.CharField(choices=[('Not provided', 'Not provided'), ('Provided', 'Provided')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 20, 14, 18, 28, 18402), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Internship', 'Internship'), ('Work and Travel', 'Work and Travel'), ('Ausbildung', 'Ausbildung')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'Bachelor’s Degree'), ('Master', 'Master’s Degree')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced'), ('Low-Intermediate', 'Low-Intermediate'), ('High-Intermediate', 'High-Intermediate'), ('Basic', 'Basic'), ('N/A', 'N/A')], max_length=255),
        ),
    ]
