# Generated by Django 4.0.6 on 2023-01-05 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_jobs_recommended_alter_jobs_housing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 5, 9, 24, 18, 677203), null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='positionLeft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantStat',
            field=models.CharField(blank=True, choices=[('Not qualified', 'Not qualified'), ('Qualified', 'Qualified')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='housing',
            field=models.CharField(choices=[('Not provided', 'Not provided'), ('Provided', 'Provided')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 1, 5, 9, 24, 18, 677243), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Work and Travel', 'Work and Travel'), ('Ausbildung', 'Ausbildung'), ('Trainee', 'Trainee'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('High-Intermediate', 'High-Intermediate'), ('Low-Intermediate', 'Low-Intermediate'), ('N/A', 'N/A'), ('Advanced', 'Advanced')], max_length=255),
        ),
    ]
