# Generated by Django 4.2.1 on 2023-05-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_alter_activestudent_answer_alter_jobs_deadline_and_more'),
        ('accounts', '0097_alter_activestudent_answer_and_more'),
    ]

    operations = [
    ]
