# Generated by Django 4.0.6 on 2023-05-29 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_alter_application_status_alter_jobs_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicantStat',
            field=models.CharField(blank=True, choices=[('Not qualified', 'Not qualified'), ('Qualified', 'Qualified')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 29, 11, 42, 32, 965841), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 5, 29, 11, 42, 32, 965879), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Work and Travel', 'Work and Travel'), ('Trainee', 'Trainee'), ('Ausbildung', 'Ausbildung'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Low-Intermediate', 'Low-Intermediate'), ('Basic', 'Basic'), ('Advanced', 'Advanced'), ('High-Intermediate', 'High-Intermediate'), ('N/A', 'N/A')], max_length=255),
        ),
    ]
