# Generated by Django 4.2.4 on 2023-10-02 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_alter_application_applicantstat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 2, 13, 43, 42, 983437), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='housing',
            field=models.CharField(choices=[('Not provided', 'Not provided'), ('Provided', 'Provided')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 2, 13, 43, 42, 983437), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Ausbildung', 'Ausbildung'), ('Trainee', 'Trainee'), ('Work and Travel', 'Work and Travel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('High-Intermediate', 'High-Intermediate'), ('Basic', 'Basic'), ('Low-Intermediate', 'Low-Intermediate'), ('Advanced', 'Advanced'), ('N/A', 'N/A')], max_length=255),
        ),
    ]
