# Generated by Django 4.2.4 on 2023-10-17 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_alter_jobs_deadline_alter_jobs_housing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 11, 59, 182905), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 17, 15, 11, 59, 182905), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Trainee', 'Trainee'), ('Ausbildung', 'Ausbildung'), ('Work and Travel', 'Work and Travel'), ('Internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type_of_work',
            field=models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Low-Intermediate', 'Low-Intermediate'), ('High-Intermediate', 'High-Intermediate'), ('Advanced', 'Advanced'), ('N/A', 'N/A'), ('Basic', 'Basic')], max_length=255),
        ),
    ]
