# Generated by Django 4.2.4 on 2023-10-17 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_alter_application_applicantstat_alter_jobs_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicantStat',
            field=models.CharField(blank=True, choices=[('Qualified', 'Qualified'), ('Not qualified', 'Not qualified')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 17, 16, 32, 11, 919949), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='housing',
            field=models.CharField(choices=[('Provided', 'Provided'), ('Not provided', 'Not provided')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 17, 16, 32, 11, 919949), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Ausbildung', 'Ausbildung'), ('Internship', 'Internship'), ('Trainee', 'Trainee'), ('Work and Travel', 'Work and Travel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='type_of_work',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Low-Intermediate', 'Low-Intermediate'), ('Advanced', 'Advanced'), ('N/A', 'N/A'), ('High-Intermediate', 'High-Intermediate')], max_length=255),
        ),
    ]
