# Generated by Django 4.2.4 on 2023-10-19 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0126_alter_application_applicantstat_alter_jobs_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 19, 10, 40, 33, 712164), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='housing',
            field=models.CharField(choices=[('Not provided', 'Not provided'), ('Provided', 'Provided')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 19, 10, 40, 33, 712164), null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='program',
            field=models.CharField(choices=[('Work and Travel', 'Work and Travel'), ('Trainee', 'Trainee'), ('Internship', 'Internship'), ('Temporary Employment', 'Temporary Employment'), ('Ausbildung', 'Ausbildung')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='degree',
            field=models.CharField(choices=[('Master', 'Master’s Degree'), ('Bachelor', 'Bachelor’s Degree')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('N/A', 'N/A'), ('Low-Intermediate', 'Low-Intermediate'), ('Advanced', 'Advanced'), ('High-Intermediate', 'High-Intermediate')], max_length=255),
        ),
    ]
