# Generated by Django 4.0.4 on 2022-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_country_alter_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Advanced', 'Advanced')], max_length=255),
        ),
    ]
