# Generated by Django 4.0.4 on 2022-06-09 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Work', '0003_alter_userlanguages_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=255)),
                ('SalaryPerHour', models.IntegerField()),
                ('TypeOfWork', models.CharField(choices=[('Full Time', 'Full Time')], max_length=50)),
                ('HourPerWork', models.IntegerField(default=0)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Housing', models.CharField(choices=[('Provided', 'Provided')], max_length=50)),
                ('HousingCostPWeek', models.IntegerField()),
                ('Program', models.CharField(choices=[('Work And Travel', 'Work And Travel')], max_length=50)),
                ('ProgramCost', models.IntegerField()),
                ('Logo', models.ImageField(upload_to='')),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20)),
                ('PostDate', models.DateField(default=datetime.datetime(2022, 6, 9, 14, 19, 55, 434859))),
                ('Approved', models.BooleanField(default=False)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.city')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplyDate', models.DateField()),
                ('Status', models.CharField(choices=[('Read', 'Read'), ('Pennding', 'Pennding')], max_length=50)),
                ('JobsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.jobs')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
