# Generated by Django 4.0.4 on 2022-06-09 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0004_jobs_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='Location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Work.city'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 14, 34, 31, 583794)),
        ),
    ]
