# Generated by Django 4.0.4 on 2022-06-09 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0007_alter_jobs_postdate_alter_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 15, 6, 37, 498225)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Status',
            field=models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=20),
        ),
    ]
