# Generated by Django 4.0.6 on 2023-05-29 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_alter_documents_users_id_document_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documents_users',
            unique_together={('id_document', 'user')},
        ),
    ]
