# Generated by Django 4.0.6 on 2023-05-31 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_alter_application_status_alter_jobs_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0003_alter_documents_users_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.CharField(choices=[('JobOffer', 'Job Offer'), ('WorkPermit', 'Work Permit')], max_length=100)),
                ('document', models.FileField(upload_to=documents.models.user_directory_path)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobs')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
