# Generated by Django 4.0.6 on 2023-05-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_recruiterdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterdocument',
            old_name='studentId',
            new_name='user',
        ),
    ]
