# Generated by Django 4.0.6 on 2023-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_studentid_recruiterdocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdocument',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Refused')], default='P', max_length=100),
        ),
    ]
