# Generated by Django 4.2.1 on 2023-06-05 12:36

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documents_users_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdocument',
            name='document',
            field=models.FileField(upload_to=documents.models.recruiter_directory_path),
        ),
    ]
