# Generated by Django 3.2.1 on 2022-07-08 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 13, 8, 53, 181903)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Elementary proficiency', 'Elementary proficiency')], max_length=255),
        ),
    ]
