# Generated by Django 3.2.1 on 2022-07-04 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 11, 23, 59, 150831)),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Elementary proficiency', 'Elementary proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Full professional proficiency', 'Full professional proficiency')], max_length=255),
        ),
    ]
