# Generated by Django 3.2.1 on 2022-07-04 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220704_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='postDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 11, 26, 2, 876969)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Elementary proficiency', 'Elementary proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Limited working proficiency', 'Limited working proficiency')], max_length=255),
        ),
    ]
