# Generated by Django 3.2.1 on 2022-06-20 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220620_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='ProfileSetup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='UserLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Advanced', 'Advanced')], max_length=255)),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.languages')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExperiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Company', models.CharField(max_length=255)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(null=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=255)),
                ('FieldOfStudy', models.CharField(max_length=255)),
                ('StartYear', models.DateField()),
                ('EndYear', models.DateField()),
                ('TotalExamplesPassed', models.IntegerField(default=0)),
                ('GPA', models.FloatField(default=0.0)),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=255)),
                ('Company', models.CharField(max_length=255)),
                ('SalaryPerHour', models.IntegerField()),
                ('TypeOfWork', models.CharField(choices=[('Full Time', 'Full Time')], max_length=50)),
                ('HourPerWork', models.IntegerField(default=0)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Housing', models.CharField(choices=[('Provided', 'Provided')], max_length=50)),
                ('HousingCostPWeek', models.IntegerField()),
                ('Program', models.CharField(choices=[('Work And Travel', 'Work And Travel')], max_length=50)),
                ('ProgramCost', models.IntegerField()),
                ('Logo', models.ImageField(upload_to='')),
                ('Description', models.TextField()),
                ('Status', models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=20)),
                ('PostDate', models.DateField(default=datetime.datetime(2022, 6, 20, 15, 8, 32, 624959))),
                ('Approved', models.BooleanField(default=False)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplyDate', models.DateField()),
                ('Status', models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], max_length=50)),
                ('JobsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jobs')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
