# Generated by Django 3.2.1 on 2022-06-20 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220620_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 16, 22, 21, 941286)),
        ),
    ]
