# Generated by Django 4.0.6 on 2022-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_jobs_apply_date_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Elementary proficiency', 'Elementary proficiency'), ('Full professional proficiency', 'Full professional proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Limited working proficiency', 'Limited working proficiency')], max_length=255),
        ),
    ]
