# Generated by Django 4.0.6 on 2022-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_birthday_alter_jobs_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Pennding', 'Pennding')], default='Pennding', max_length=50),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Elementary proficiency', 'Elementary proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Full professional proficiency', 'Full professional proficiency')], max_length=255),
        ),
    ]
