# Generated by Django 4.0.6 on 2022-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_application_status_alter_userlanguages_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pennding', 'Pennding'), ('Read', 'Read')], default='Pennding', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='default.jpeg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='logo',
            field=models.ImageField(upload_to='JobLogo'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Close', 'Close'), ('Open', 'Open')], default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlanguages',
            name='level',
            field=models.CharField(choices=[('Native or bilingual proficiency', 'Native or bilingual proficiency'), ('Limited working proficiency', 'Limited working proficiency'), ('Elementary proficiency', 'Elementary proficiency'), ('Professional working proficiency', 'Professional working proficiency'), ('Full professional proficiency', 'Full professional proficiency')], max_length=255),
        ),
    ]
