# Generated by Django 3.2.1 on 2022-06-21 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220621_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(choices=[('Read', 'Read'), ('Pennding', 'Pennding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='download.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 21, 13, 44, 38, 983435)),
        ),
    ]
