# Generated by Django 4.0.5 on 2022-06-28 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220621_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Status',
            field=models.CharField(choices=[('Read', 'Read'), ('Pennding', 'Pennding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 28, 9, 11, 45, 656508)),
        ),
    ]
