# Generated by Django 4.0.5 on 2022-06-28 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_country_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='PostDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 28, 13, 43, 49, 227430)),
        ),
    ]
