# Generated by Django 4.0.6 on 2022-11-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_activestudent_answer_alter_jobs_housing_and_more'),
        ('Applicant', '0002_applicantsubphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantsubphase',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.jobs'),
        ),
    ]
