# Generated by Django 4.1.5 on 2023-01-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0004_phase_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantsubphase',
            old_name='applicant',
            new_name='user_id',
        ),
    ]
