# Generated by Django 4.2.1 on 2023-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0005_rename_applicant_applicantsubphase_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantsubphase',
            name='subPhase',
            field=models.CharField(max_length=255),
        ),
    ]
